name: Code Check

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read

env:
  PYTHON_VERSION: '3.10'
  POETRY_VERSION: '1.2.0'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: '**/pyproject.toml'
      - name: Cache poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: poetry-cache-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ env.POETRY_VERSION }}-${{ hashfiles('poetry.lock') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry==${{ env.POETRY_VERSION }}
          poetry install
      - name: Lint
        run: make lint
      - name: Format check
        run: make format-check
      - name: Type check
        run: make typecheck
      - name: Test
        run: make test
